services:
  db:
    image: mongodb/mongodb-atlas-local
    hostname: mongodb
    ports:
      - "27017:27017"
    environment:
      - MONGODB_INITDB_ROOT_USERNAME=${MONGODB_USER}
      - MONGODB_INITDB_ROOT_PASSWORD=${MONGODB_PASSWORD}
    volumes:
      - ./init:/docker-entrypoint-initdb.d
      - db:/data/db
      - configdb:/data/configdb
      - mongot:/data/mongot
volumes:
  db:
  configdb:
  mongot:
